removed github stats and licenses from security card
fabric8-analytics/fabric8-analytics-stack-report-ui pull request #166
Opened 2020-09-25 17:26 UTC by sawood14012

# Discription

Removed Github Status and Licenses from Security tab and made vulnerability details come after recommended versions card in security details card 

- [X] Removed Github Status 
- [X]  Removed Licenses 
- [X]  Moved Vulnerbility details card to left

2020-09-28 05:53 UTC, arajkumar requested changes
@sawood14012 I see only view changes, the corresponding view model also should be modified.

CC: @mathur07

2020-09-28 06:08 UTC, sawood14012 commented
> @sawood14012 I see only view changes, the corresponding view model also should be modified.
> 
> CC: @mathur07

@arajkumar i dont think any model changes are required because i have just used whatever was previously present and modified the changes.

2020-09-28 13:28 UTC, mathur07 commented
@arajkumar ya only view changes are required..

2020-09-28 13:29 UTC, mathur07 approved these changes
https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.dictionary.com%2Fe%2Fwp-content%2Fuploads%2F2018%2F05%2Flhtm-300x300.jpg&imgrefurl=https%3A%2F%2Fwww.dictionary.com%2Fe%2Facronyms%2Flgtm%2F&tbnid=s9GZH1gcwmGxsM&vet=12ahUKEwiUtfSw-ovsAhXbi0sFHWdEBtwQMygAegUIARCTAQ..i&docid=2_KVXwFv6QWnxM&w=300&h=300&q=lgtm&ved=2ahUKEwiUtfSw-ovsAhXbi0sFHWdEBtwQMygAegUIARCTAQ

2020-09-28 14:30 UTC, arajkumar requested changes

2020-09-28 14:30 UTC, arajkumar commented on src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
> +                        <!-- </span> -->
Remove the commented code.

2020-09-28 14:32 UTC, sawood14012 commented
Before : 
![Screenshot from 2020-09-28 19-36-48](https://user-images.githubusercontent.com/18240985/94445800-81a21400-01c5-11eb-94d4-2cbf0aee8afa.png)

2020-09-28 14:33 UTC, sawood14012 commented
After : 
![Screenshot from 2020-09-28 19-41-19](https://user-images.githubusercontent.com/18240985/94445882-9aaac500-01c5-11eb-973e-c0e1d338106b.png)

2020-09-28 14:35 UTC, sawood14012 commented on src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
> +    <div *ngIf="view === 'normal' && !component.isTransitive && tabType =='compDetails'" class="github-osio-box">
yup looks redundant but it was from a long time so i didn't touch it will check and change

2020-09-28 14:35 UTC, sawood14012 commented on src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
> +                        <!-- </span> -->
okay

2020-09-28 15:30 UTC, sawood14012 commented on src/app/stack/card-details/component-information/component-snippet/component-snippet.component.html
> +    <div *ngIf="view === 'normal' && !component.isTransitive && tabType =='compDetails'" class="github-osio-box">
you were right removed it

2020-09-29 05:29 UTC, arajkumar approved these changes
lgtm

2020-09-29 06:05 UTC, merged