fix: Unique to Snyk Highest Severity Vulnerability text issue
fabric8-analytics/fabric8-analytics-stack-report-ui pull request #170
Opened 2020-10-06 09:20 UTC by mathur07

2020-10-06 09:23 UTC, mathur07 commented
[test]

2020-10-06 09:32 UTC, mathur07 commented
@arunkumars08 when using old plugin against new SA-UI this issue occurred.

2020-10-06 09:42 UTC, arajkumar requested changes

2020-10-06 09:42 UTC, arajkumar commented on src/app/stack/card-details/component-information/component-information.component.html
> +                                <span *ngIf="comp?.registrationStatus !== 'registered' && comp?.privateSecurityDetails && comp?.privateSecurityDetails?.highestIssue?.cve">
```suggestion
                                <span *ngIf="comp?.registrationStatus !== 'registered' &&  comp?.privateSecurityDetails?.highestIssue?.cve">
```

2020-10-06 09:55 UTC, arajkumar approved these changes
lgtm

2020-10-07 09:40 UTC, mathur07 commented
[test]

2020-10-07 10:54 UTC, mathur07 commented
[test]

2020-10-07 11:28 UTC, mathur07 commented
[test]

2020-10-07 11:52 UTC, mathur07 commented
[test]

2020-10-07 12:10 UTC, mathur07 commented
[test]

2020-10-07 12:38 UTC, mathur07 commented
[test]

2020-10-07 12:50 UTC, mathur07 commented
[test]

2020-10-07 15:01 UTC, mathur07 commented
[test]

2020-10-07 16:41 UTC, mathur07 commented
[test]

2020-10-08 05:26 UTC, mathur07 commented
[test]

2020-10-08 07:55 UTC, mathur07 commented
[test]

2020-10-08 12:29 UTC, mathur07 commented
[test]

2020-10-09 08:55 UTC, merged