fix: Remove ctrl/cmd+click text
fabric8-analytics/fabric8-analytics-stack-report-ui pull request #174
Opened 2020-11-05 08:00 UTC by mathur07

2020-11-05 10:55 UTC, sawood14012 approved these changes
LGTM

2020-11-06 06:39 UTC, arajkumar commented on src/app/stack/card-details/report-information/report-information.component.html
>                  (click)="this.handleUrl.open($event, this.generateUrl.registrationURL)"><button class="ripple">Sign up for
Shouldn't we do preventDefault on the click event?

2020-11-06 07:33 UTC, mathur07 commented on src/app/stack/card-details/report-information/report-information.component.html
>                  (click)="this.handleUrl.open($event, this.generateUrl.registrationURL)"><button class="ripple">Sign up for
Ya correct, I forgot to do that. Added it now.

2020-11-06 10:07 UTC, arajkumar requested changes
There is a garbage file " Paste doesn't activate token Submit button". Please remove.
https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/blob/c2bc95252f59e352bd4f44705e8537ee49d6136c/Paste%20doesn't%20activate%20token%20Submit%20button

2020-11-06 10:10 UTC, mathur07 commented
@arajkumar yes, I have removed the garbage file.

2020-11-06 11:07 UTC, arajkumar approved these changes
lgtm

2020-11-06 13:36 UTC, merged